["autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h" # update weekly

["syntax/gomod.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/fatih/vim-go/master/syntax/gomod.vim"
    refreshPeriod = "168h" # update weekly
