[".fzf"]
    type = "archive"
    url = "https://github.com/junegunn/fzf/archive/refs/tags/{{ template "fzfVersion" }}.tar.gz"
    exact = true
    stripComponents = 1

[".local/share/nvim/site/pack/packer/start/packer.nvim"]
    type = "archive"
    url = "https://github.com/wbthomason/packer.nvim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    # Don't refresh -- packer manages itself after bootstrapping.
