appearance = "dark"  # dark mode detection doesn't always work
leader = ","
wrap = true
transparent_background = true
scroll_offset = 3
no_update_check = true
ignore_whitespace = true
comment_types = [
  { id = "issue", color = "yellow", definition = "issue, bug, or problem" },
  { id = "doc", color = "cyan", definition = "documentation or comment change or request" },
  { id = "optional", color = "blue", definition = "optional suggestion" },
  { id = "blocker", color = "red", definition = "must be fixed before merging" },
]

[forge]
comment_type_prefix = false
