#!/bin/zsh

setopt autocd       # Executing a directory cds into it
setopt autopushd    # pushd instead of cd
setopt pushd_ignoredups
                    # No duplicate entries in pushd
setopt cdablevars   # cd VAR == cd $VAR if $VAR is a directory
