#!/bin/zsh

if (command -v direnv &> /dev/null); then
    _direnv_hook() {
      eval "$("/usr/local/bin/direnv" export zsh)";
    }

    typeset -ag precmd_functions;
    if [[ -z ${precmd_functions[(r)_direnv_hook]} ]]; then
      precmd_functions+=_direnv_hook;
    fi
fi
