#!/bin/zsh

export FZF_DEFAULT_OPTS="--cycle"
export FZF_DEFAULT_COMMAND='
  (rg --hidden --files || git ls-tree -r --name-only HEAD ||
   find . -path "*/\.*" -prune -o -type f -print -o -type l -print |
      sed s/^..//) 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND='
  (git ls-tree -d -r --name-only HEAD ||
   find -L . \( -path "*/\.*" -o -fstype dev -o -fstype proc \) -prune -o -type d -print |
      sed 1d | cut -b3-) 2> /dev/null'

unset fzf_search_command

if [[ -d "/usr/share/fzf" ]]; then
	_fzf_shell="/usr/share/fzf"
elif [[ -d "/opt/homebrew/opt/fzf/shell" ]]; then
	_fzf_shell="/opt/homebrew/opt/fzf/shell"
fi

if [[ -n "${_fzf_shell:-}" ]]; then
	source "${_fzf_shell}/completion.zsh" 2> /dev/null
	source "${_fzf_shell}/key-bindings.zsh"
	unset _fzf_shell
fi

