#!/bin/zsh

source ~/.zsh/fzf-tab-completion/zsh/fzf-zsh-completion.sh

export FZF_COMPLETION_OPTS='--bind=tab:down --bind=btab:up'

# completion previews for ls, exa, and cd.
zstyle ':completion::*:(ls|eza)::*' fzf-completion-opts --preview='
	P=$(eval echo {1})
	if [ -f "$P" ]; then
		bat --color=always "$P"
	else
		eza -1 --color=always "$P"
	fi
'
# For cd, use eza to show previews of directories,
# and accept them with / to continue chaning directories.
zstyle ':completion::*:cd::*' \
	fzf-completion-opts --preview='eval eza -1 --color=always {1}'

zstyle ':completion::*:(cd|ls|eza)::*' \
	fzf-completion-keybindings  /:accept:'repeat-fzf-completion'

# Show log previews for git-log.
zstyle ':completion::*:git::git,log,*' fzf-completion-opts \
	--preview='eval git log --oneline --color=always {1}'
