#!/bin/zsh

# Expand parameters, command substitution, etc. in prompts.
setopt PROMPT_SUBST

autoload -U colors
colors

if [ "$ITERM_PROFILE" = "Presentation" ]; then
    export PROMPT='%{$fg[blue]%} $ %{$reset_color%}'
    return
fi

local ret_status="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ %s)"

# Indicate with red <<< on the right when in normal mode.
function zle-key-map-init zle-keymap-select {
    zle reset-prompt
    zle -R
}

zle -N zle-keymap-init
zle -N zle-keymap-select

MODE_INDICATOR="%{$fg_bold[red]%}<<<%{$reset_color%}"
function vi_mode_indicator() {
    echo "${${KEYMAP/vicmd/$MODE_INDICATOR}/(main|viins)/}"
}
RPS1='$(vi_mode_indicator)'

function cabal_sandbox_info() {
    if [ -f cabal.sandbox.config ]; then
        echo "%{$fg[green]%}sandboxed%{$reset_color%}"
    else
        if [ -d .stack-work ]; then
            echo "%{$fg[green]%}stack%{$reset_color%}"
        else
        cabal_files=(*.cabal(N))
            if [ $#cabal_files -gt 0 ]; then
                echo "%{$fg[red]%}not sandboxed%{$reset_color%}"
            fi
        fi
    fi
}

_GITPROMPT=$(command -v gitprompt)
if [ -z "$_GITPROMPT" ]; then
    _GITPROMPT='echo (gitprompt is not installed)'
else
	_GITPROMPT="$_GITPROMPT zsh"
fi

PROMPT='%{$fg_bold[white]%}%M%{$reset_color%} ${ret_status}%{$fg_bold[green]%}%p %{$fg[cyan]%}%~ %{$reset_color%}$($_GITPROMPT) $(cabal_sandbox_info)
%{$fg[blue]%} $ %{$reset_color%}'
