#!/bin/bash

# Use synapse as our app launcher. (-s: don't display until requested)
if [ -z "$(pgrep synapse)" ] ; then
    synapse -s &
fi

if [ -z "$(pgrep synergys)" ] ; then
    synergys --daemon --log "$HOME/.synergys.log"
fi


