#!/usr/bin/env python3

"""
Returns the ID for the next or previous space relative to the focused window
on the same display.
"""

import argparse
import json
import os
import subprocess
import sys

def main(args):
    parser = argparse.ArgumentParser()
    parser.add_argument("direction", choices=["next", "prev"])
    args = parser.parse_args(args)

    stdout = subprocess.check_output(
        ["yabai", "-m", "query", "--spaces", "--display"],
    )
    spaces = sorted(
        json.loads(stdout.decode("utf-8")),
        key=lambda s: s["index"],
    )

    for idx, space in enumerate(spaces):
        if not space["has-focus"]:
            continue

        target = None
        if args.direction == "next":
            next_idx = idx + 1
            if next_idx >= len(spaces):
                sys.exit(1)
            target = spaces[next_idx]
        elif args.direction == "prev":
            prev_idx = idx - 1
            if prev_idx < 0:
                sys.exit(1)
            target = spaces[prev_idx]

        if target:
            print(target["index"])
            sys.exit(0)

    sys.exit(1)


if __name__ == "__main__":
    main(sys.argv[1:])
