#!/bin/zsh

# Expand parameters, command substitution, etc. in prompts.
setopt PROMPT_SUBST

autoload -U colors
colors

if [ "$ITERM_PROFILE" = "Presentation" ]; then
    export PROMPT='%{$fg[blue]%} $ %{$reset_color%}'
    return
fi

local ret_status="%(?:%{$fg_bold[green]%}#:%{$fg_bold[red]%}#%s)"

_GITPROMPT=$(command -v gitprompt)
if [ -z "$_GITPROMPT" ]; then
    _GITPROMPT='echo (gitprompt is not installed)'
else
	_GITPROMPT="$_GITPROMPT zsh"
fi

PROMPT='${ret_status}%{$fg_bold[green]%} %{$fg[cyan]%}%~ %{$reset_color%}$($_GITPROMPT)
%{$fg[blue]%}%% %{$reset_color%}'
