tap "homebrew/cask-fonts"
tap "homebrew/bundle"
tap "abhinav/tap"

brew "bat"        # > cat
brew "curl"
brew "eza"        # > ls
brew "fzf"        # fuzzy match
brew "go"
brew "gopls"
brew "hyperfine"  # CLI benchmarks
brew "jq"         # JSON munging
brew "gron"       # JSON grepping
brew "jless"      # JSON reading
brew "node"
brew "pandoc"
brew "pv"
brew "python"
brew "ripgrep"    # > grep
brew "rustup"
brew "shellcheck" # lint .sh
brew "starship"   # prompt
brew "shfmt"
brew "stow"
brew "tmux"
brew "abhinav/tap/tmux-fastcopy"
brew "watch"

# Shell and friends.
brew "direnv"
brew "zoxide"  # cd from/to anywhere
brew "zsh"
brew "zsh-completions"
brew "gawk" # for fzf-tab-completion
brew "grep" # for fzf-tab-completion

# Editing.
tap "neovim/neovim"
brew "neovim", args: ["HEAD"]
brew "svn"  # needed weirdly for the font
cask "font-iosevka"
cask "font-iosevka-nerd-font"
cask "espanso"             # text expansion

# Git and friends.
brew "git"
brew "git-absorb"  # automatic fixup commits
brew "git-delta"   # git pager
brew "git-lfs"
brew "tig"
tap "github/gh"
brew "gh"
brew "abhinav/tap/restack"

cask "1password"
cask "appcleaner"
cask "caffeine"      # don't sleep
cask "firefox"
cask "flux"
cask "google-drive"
cask "iterm2"
cask "kap"           # screen cap
cask "licecap"       # ^
cask "little-snitch" # firewall
cask "obsidian"      # notes
cask "spotify"

cask "alfred"              # command space
cask "hammerspoon"         # window management
cask "karabiner-elements"  # keyboard control
cask "spaceman"            # report current space in menu gar
cask "scroll-reverser"     # use normal scrolling on mouse
cask "sensiblesidebuttons" # back/fwd with mouse

# vim:set ft=ruby:
