#!/bin/bash

# If we're using a vim-ey editor, use it as the pager for 'man'.
if [[ "$EDITOR" == *vim ]]; then
	# "sh -c" so that we can pipe.
	MANPAGER="/bin/sh -c \"col -b | $EDITOR -c 'set ft=man ts=8 nolist nonu' -MR -\""
	export MANPAGER
fi
