#!/bin/sh

_setup_nvm_alias()
{
	name="$1"
	eval "
		$name()
		{
			unset -f $name
			if [ -z \"\$NVM_DIR\" ]; then
				. '$HOME/.nvm/nvm.sh'
			fi
			$name \"\$@\"
		}
	"
}

setup_nvm_aliases()
{
	_setup_nvm_alias nvm
	_setup_nvm_alias npm
	_setup_nvm_alias node
}

if [ -e "$HOME/.nvm/nvm.sh" ]; then
	setup_nvm_aliases
fi

unset -f _setup_nvm_alias setup_nvm_aliases
