#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Uses rsync hard links to create incremental backups.
# Backups are stored at /var/data/backups/YYYY/MM/DD/HHMMSS.
#
# Setup:
#
#   sudo mkdir -p /var/data/backups
#   sudo chown $USER /var/data/backups
#
# Schedule (Linux):
#
#   0 */12 * * * bash ~/tools/rsync-time-machine
#
# Schedule (macOS):
#
#   launchctl load ~/Library/LaunchAgents/rsync-time-machine.plist
#   launchctl start rsync-time-machine
#
# Inspiration:
# - https://linuxconfig.org/how-to-create-incremental-backups-using-rsync-on-linux
# - https://samuelhewitt.com/blog/2018-06-05-time-machine-style-backups-with-rsync
# - https://github.com/jcorbin/home/blob/5054bfa7521d6e7dd2a6118f2876d942d5572e7c/.local/bin/home-backup

readonly BACKUP_DIR="/var/data/backups"

TIMESTAMP=$(TZ=UTC date +%Y/%U/%w/%H%M)
readonly BACKUP_PATH="${BACKUP_DIR}/${TIMESTAMP}"
readonly LATEST_LINK="${BACKUP_DIR}/latest"
readonly LOG_FILE="${BACKUP_DIR}/logs/${TIMESTAMP}.log"

ARGS=(
	--archive --one-file-system --quiet
	--link-dest="${LATEST_LINK}"
	--log-file="${LOG_FILE}"
	--filter ":- .backup-exclude"
)
ARGS+=("$HOME/" "${BACKUP_PATH}")

mkdir -p "${BACKUP_PATH}" "$(dirname "${LOG_FILE}")"
rsync "${ARGS[@]}"
rm -rf "${LATEST_LINK}"
ln -s "${BACKUP_PATH}" "${LATEST_LINK}"
