#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Uses rsync hard links to create incremental backups.
# Backups are stored at /var/data/backups/YYYY/MM/DD/HHMMSS.
#
# Setup:
#
#   sudo mkdir -p /var/data/backups
#   sudo chown $USER /var/data/backups
#
# Run 'crontab -e', and add:
#
#   0 */12 * * * bash ~/tools/rsync-time-machine
#
# Inspiration:
# - https://linuxconfig.org/how-to-create-incremental-backups-using-rsync-on-linux
# - https://samuelhewitt.com/blog/2018-06-05-time-machine-style-backups-with-rsync

readonly SRCS=(
	Desktop
	Documents
	Downloads
	src
)
readonly EXCLUSIONS=(
	"node_modules"
	"zig-cache"
	"zig-out"
	".vscode"
	".DS_Store"
)
readonly BACKUP_DIR="/var/data/backups"

TIMESTAMP=$(date '+%Y/%m/%d/%H%M%S')
readonly BACKUP_PATH="${BACKUP_DIR}/${TIMESTAMP}"
readonly LATEST_LINK="${BACKUP_DIR}/latest"
readonly LOG_FILE="${BACKUP_DIR}/logs/${TIMESTAMP}.log"

ARGS=(
	--archive --verbose --delete
	--link-dest="${LATEST_LINK}"
)
for X in "${EXCLUSIONS[@]}"; do
	ARGS+=("--exclude=${X}")
done
ARGS+=("${SRCS[@]}" "${BACKUP_PATH}")

mkdir -p "${BACKUP_PATH}" "$(dirname "${LOG_FILE}")"
rsync "${ARGS[@]}" > "${LOG_FILE}" 2>&1
rm -rf "${LATEST_LINK}"
ln -s "${BACKUP_PATH}" "${LATEST_LINK}"
