#!/bin/bash

# cd's up to the next boundary parent boundary.
# boundaries are defined by project or repository markers.
function cdup() {
	readonly _boundaries=(
		.git
		build.zig
		Cargo.toml
		Gemfile
		go.mod
		Makefile
		package.json
		pyproject.toml
		yarn.lock
	)

	local dir
	dir=$(dirname "$(pwd)")
	while [[ $dir != "/" ]]; do
		for boundary in "${_boundaries[@]}"; do
			if [[ -e "$dir/$boundary" ]]; then
				cd "$dir" || return 1
				return 0
			fi
		done
		dir=$(dirname "$dir")
	done
}
