#!/bin/bash

EDITOR=vim
if command -v nvim &> /dev/null; then
	EDITOR=nvim
fi
export EDITOR
export HOMEBREW_EDITOR="$EDITOR"

export NEOVIDE_MULTIGRID=1
if [[ "$(uname)" == "Darwin" ]]; then
	export NEOVIDE_FRAME=buttonless
	export NEOVIDE_SCALE_FACTOR=1.3
else
	export NEOVIDE_FRAME=none
fi
