#!/bin/bash

if [ -d "$HOMEBREW_PREFIX/opt/go/libexec/bin" ]; then
	# shellcheck disable=2086
	PATH=$(IFS=:; prepend "$HOMEBREW_PREFIX/opt/go/libexec/bin" $PATH)
fi

GOPATH="$HOME/go"
if [ -d "$HOME/dev/.go" ]; then
	GOPATH="$HOME/dev/.go"
fi
export GOPATH

# shellcheck disable=2086
PATH=$(IFS=:; prepend "$GOPATH/bin" $PATH)

export PATH
