#!/bin/bash

export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_PREFIX=/usr/local

# Check for updates once a week.
export HOMEBREW_AUTO_UPDATE_SECS=604800

# shellcheck disable=2086
PATH=$(IFS=:; prepend "$HOMEBREW_PREFIX/bin" $PATH)
export PATH
