#!/bin/bash

export HOMEBREW_NO_ANALYTICS=1

if [[ "$(uname)" == Darwin ]]; then
	if [[ -d /opt/homebrew ]]; then
		HOMEBREW_PREFIX=/opt/homebrew
	elif [[ -d /usr/local/Homebrew ]]; then
		HOMEBREW_PREFIX=/usr/local
	fi
elif [[ "$(uname)" == Linux ]]; then
	if [[ -d /home/linuxbrew/.linuxbrew ]]; then
		HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew
	fi
fi

if [[ -n "${HOMEBREW_PREFIX:-}" ]]; then
	export HOMEBREW_PREFIX

	# Check for updates once a week.
	export HOMEBREW_AUTO_UPDATE_SECS=604800

	# shellcheck disable=2086
	PATH=$(IFS=:; prepend "$HOMEBREW_PREFIX/sbin" $PATH)
	# shellcheck disable=2086
	PATH=$(IFS=:; prepend "$HOMEBREW_PREFIX/bin" $PATH)
	export PATH

	# shellcheck disable=2086
	MANPATH=$(IFS=:; prepend "$HOMEBREW_PREFIX/share/man" $MANPATH)
	export MANPATH

	# shellcheck disable=2086
	INFOPATH=$(IFS=:; prepend "$HOMEBREW_PREFIX/share/info" $INFOPATH)
	export INFOPATH
fi
