#!/bin/sh

if [ -e "$HOME/.nvm/nvm.sh" ]; then
	if [ -f "$HOME/.nvm/alias/default" ]; then
		nvm_default=$(cat "$HOME/.nvm/alias/default")
		if [ -d "$HOME/.nvm/v${nvm_default}/bin" ]; then
			export PATH=$(IFS=:; prepend "$HOME/.nvm/v${nvm_default}/bin" $PATH)
		else
			export PATH=$(IFS=:; prepend "$HOME/.nvm/versions/node/v${nvm_default}/bin" $PATH)
		fi
	fi

	nvm()
	{
		. "$HOME/.nvm/nvm.sh"
		nvm "$@"
	}
fi

export PATH=$(IFS=:; prepend "node_modules/.bin" $PATH)
