[tool_alias]
betamax = "github:joshka/betamax"

[tools]
betamax = "latest"
go = "latest"
gofumpt = "latest"
golangci-lint = "latest"
rust = "latest"
revdiff = "latest"
zig = "latest"

[settings]
experimental = true
go_set_gobin = false
lockfile = true
env_shell_expand = true
auto_env = true
