[tools]
go = "latest"
gofumpt = "latest"
golangci-lint = "latest"
rust = "latest"
zig = "latest"
"github:abhinav/cardamom" = { version = "latest", exe = "card" }
"github:abhinav/tmux-fastcopy" = "latest"
"github:kunchenguid/treehouse" = "latest"
"github:umputun/revdiff" = "latest"
pitchfork = "latest"
"aqua:benbjohnson/litestream" = "latest"

[settings]
experimental = true
go_set_gobin = false
lockfile = true
env_shell_expand = true
auto_env = true
